name: CI/CD - Proxy

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t proxy .
      
      - name: Tags
        run: |
          docker tag proxy ${{ secrets.DOCKER_ORGANIZATION }}/proxy:release-${{ github.sha }}
          docker tag proxy ${{ secrets.DOCKER_ORGANIZATION }}/proxy:latest

      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_ORGANIZATION }}/proxy:release-${{ github.sha }}
          docker push ${{ secrets.DOCKER_ORGANIZATION }}/proxy:latest